# Generated by Django 5.1.4 on 2025-03-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orpho_name', models.CharField(max_length=100)),
                ('orpho_type', models.CharField(max_length=50)),
                ('orpho_city', models.CharField(max_length=100)),
                ('orpho_email', models.EmailField(max_length=254)),
                ('orpho_caretaker_name', models.CharField(max_length=100)),
                ('orpho_no_residentials', models.IntegerField()),
                ('orpho_contact_no', models.IntegerField()),
                ('orpho_address', models.TextField()),
                ('orpho_description', models.TextField()),
                ('orpho_requirements', models.TextField()),
                ('orpho_image', models.ImageField(upload_to='orpho_images')),
            ],
        ),
        migrations.CreateModel(
            name='Orphanage_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_message', models.TextField()),
                ('sender_rating', models.IntegerField()),
            ],
        ),
    ]
