# Generated by Django 5.1.4 on 2025-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_add_orphanage_orpho_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanage_feedback',
            name='sender_message',
            field=models.CharField(max_length=500),
        ),
    ]
